'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { useTheme } from '@emotion/react'
import { useSettings } from 'src/hooks/useSettings'
import CustomTextField from 'src/components/text-field'
import { Box } from '@mui/material'
import Link from 'next/link'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()

  console.log('Theme', { theme, settings })
  
  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button variant='contained'>Hello world updated</Button>
      <Box sx={{ margin: 6 , width: "200%" }}>
        <CustomTextField id="demo-helper-text-misaligned-no-helper" label='Uncontrolled' />
        <Link href={'/login'}>pageLogin</Link>
      </Box>
    </>
  )
}
